In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [4]:
df = pd.read_csv("D:\Pics_Docs_for_proj\ipl_data\IPL_Data.csv")
df1 = pd.read_csv("D:\Pics_Docs_for_proj\ipl_data\T20_Data.csv")

In [5]:
df

,Name,Team,Url,Type,ValueinCR,Full Name,Born,Age,National Side,Batting Style,...,Maidens,RunsConceded,Wickets,Best,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
0,Mayank Agarwal,PBKS,https://sports.ndtv.com/cricket/players/1430-m...,Batsman,12.00,Mayank Anurag Agarwal,"February 16, 1991 Bangalore, Karnataka","31 Years, 0 Months, 28 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Liam Livingstone,PBKS,https://sports.ndtv.com/cricket/players/64363-...,All-Rounder,11.50,Liam Stephen Livingstone,"August 4, 1993 Barrow-in-Furness, Cumberland","28 Years, 7 Months, 11 Days",England,Right Handed,...,0.0,13.0,0.0,0/13 v MI,0.0,0.0,NaN,13.00,NaN,1.0
2,Kagiso Rabada,PBKS,https://sports.ndtv.com/cricket/players/64042-...,Bowler,9.25,Kagiso Rabada,"May 25, 1995 Johannesburg","26 Years, 9 Months, 22 Days",South Africa,Left Handed,...,2.0,1560.0,76.0,4/21 v RCB,4.0,0.0,20.52,8.21,15.00,50.0
3,Shahrukh Khan,PBKS,https://sports.ndtv.com/cricket/players/113433...,All-Rounder,9.00,Masood Shahrukh Khan,"May 27, 1995 Chennai, Tamil Nadu","26 Years, 9 Months, 20 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Shikhar Dhawan,PBKS,https://sports.ndtv.com/cricket/players/737-sh...,Batsman,8.25,Shikhar Dhawan,"December 5, 1985 Delhi","36 Years, 3 Months, 10 Days",India,Left Handed,...,0.0,66.0,4.0,1/7 v DC,0.0,0.0,16.50,8.25,12.00,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,Gurkeerat Singh Mann,GT,https://sports.ndtv.com/cricket/players/1661-g...,All-Rounder,0.50,Gurkeerat Rupinder Singh,"June 29, 1990 Muktsar, Punjab","31 Years, 8 Months, 16 Days",India,Right Handed,...,0.0,97.0,5.0,2/15 v RPS,0.0,0.0,19.40,7.46,15.60,6.0
233,Noor Ahmad,GT,https://sports.ndtv.com/cricket/players/112545...,Bowler,0.30,Noor Ahmad Lakanwal,"January 3, 2005","17 Years, 2 Months, 12 Days",Afghanistan,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,Darshan Nalkande,GT,https://sports.ndtv.com/cricket/players/110589...,All-Rounder,0.20,Darshan Girish Nalkande,"October 4, 1998 Wardha, Maharashtra","23 Years, 5 Months, 11 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Sai Sudharsan,GT,https://sports.ndtv.com/cricket/players/115302...,All-Rounder,0.20,Bhardwaj Sai Sudharsan,"October 15, 2001","20 Years, 5 Months, 0 Days",India,Left Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,Pradeep Sangwan,GT,https://sports.ndtv.com/cricket/players/1047-p...,All-Rounder,0.20,Pradeep Jaibeer Sangwan,"November 5, 1990 Rasiwas, Delhi","31 Years, 4 Months, 10 Days",India,Right Handed,...,1.0,1175.0,35.0,3/18 v DCH,3.0,0.0,33.57,8.79,22.91,39.0

In [6]:
df1

,Name,Team,Url,Type,ValueinCR,Full Name,Born,Age,National Side,Batting Style,...,Maidens,RunsConceded,Wickets,Best,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
0,Mayank Agarwal,PBKS,https://sports.ndtv.com/cricket/players/1430-m...,Batsman,12.00,Mayank Anurag Agarwal,"February 16, 1991 Bangalore, Karnataka","31 Years, 0 Months, 28 Days",India,Right Handed,...,0.0,51.0,2.0,1/4 v RS,0.0,0.0,25.50,5.56,27.50,6.0
1,Liam Livingstone,PBKS,https://sports.ndtv.com/cricket/players/64363-...,All-Rounder,11.50,Liam Stephen Livingstone,"August 4, 1993 Barrow-in-Furness, Cumberland","28 Years, 7 Months, 11 Days",England,Right Handed,...,0.0,235.0,12.0,2/15 v BAN,0.0,0.0,19.58,7.12,16.50,12.0
2,Kagiso Rabada,PBKS,https://sports.ndtv.com/cricket/players/64042-...,Bowler,9.25,Kagiso Rabada,"May 25, 1995 Johannesburg","26 Years, 9 Months, 22 Days",South Africa,Left Handed,...,0.0,1245.0,49.0,3/20 v BAN,5.0,0.0,25.40,8.57,17.77,40.0
3,Shahrukh Khan,PBKS,https://sports.ndtv.com/cricket/players/113433...,All-Rounder,9.00,Masood Shahrukh Khan,"May 27, 1995 Chennai, Tamil Nadu","26 Years, 9 Months, 20 Days",India,Right Handed,...,0.0,163.0,1.0,1/20 v CSG,0.0,0.0,163.00,9.05,108.00,9.0
4,Shikhar Dhawan,PBKS,https://sports.ndtv.com/cricket/players/737-sh...,Batsman,8.25,Shikhar Dhawan,"December 5, 1985 Delhi","36 Years, 3 Months, 10 Days",India,Left Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,Gurkeerat Singh Mann,GT,https://sports.ndtv.com/cricket/players/1661-g...,All-Rounder,0.50,Gurkeerat Rupinder Singh,"June 29, 1990 Muktsar, Punjab","31 Years, 8 Months, 16 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,Noor Ahmad,GT,https://sports.ndtv.com/cricket/players/112545...,Bowler,0.30,Noor Ahmad Lakanwal,"January 3, 2005","17 Years, 2 Months, 12 Days",Afghanistan,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,Darshan Nalkande,GT,https://sports.ndtv.com/cricket/players/110589...,All-Rounder,0.20,Darshan Girish Nalkande,"October 4, 1998 Wardha, Maharashtra","23 Years, 5 Months, 11 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Sai Sudharsan,GT,https://sports.ndtv.com/cricket/players/115302...,All-Rounder,0.20,Bhardwaj Sai Sudharsan,"October 15, 2001","20 Years, 5 Months, 0 Days",India,Left Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,Pradeep Sangwan,GT,https://sports.ndtv.com/cricket/players/1047-p...,All-Rounder,0.20,Pradeep Jaibeer Sangwan,"November 5, 1990 Rasiwas, Delhi","31 Years, 4 Months, 10 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.head()

,Name,Team,Url,Type,ValueinCR,Full Name,Born,Age,National Side,Batting Style,...,Maidens,RunsConceded,Wickets,Best,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
0,Mayank Agarwal,PBKS,https://sports.ndtv.com/cricket/players/1430-m...,Batsman,12.00,Mayank Anurag Agarwal,"February 16, 1991 Bangalore, Karnataka","31 Years, 0 Months, 28 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Liam Livingstone,PBKS,https://sports.ndtv.com/cricket/players/64363-...,All-Rounder,11.50,Liam Stephen Livingstone,"August 4, 1993 Barrow-in-Furness, Cumberland","28 Years, 7 Months, 11 Days",England,Right Handed,...,0.0,13.0,0.0,0/13 v MI,0.0,0.0,NaN,13.00,NaN,1.0
2,Kagiso Rabada,PBKS,https://sports.ndtv.com/cricket/players/64042-...,Bowler,9.25,Kagiso Rabada,"May 25, 1995 Johannesburg","26 Years, 9 Months, 22 Days",South Africa,Left Handed,...,2.0,1560.0,76.0,4/21 v RCB,4.0,0.0,20.52,8.21,15.0,50.0
3,Shahrukh Khan,PBKS,https://sports.ndtv.com/cricket/players/113433...,All-Rounder,9.00,Masood Shahrukh Khan,"May 27, 1995 Chennai, Tamil Nadu","26 Years, 9 Months, 20 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Shikhar Dhawan,PBKS,https://sports.ndtv.com/cricket/players/737-sh...,Batsman,8.25,Shikhar Dhawan,"December 5, 1985 Delhi","36 Years, 3 Months, 10 Days",India,Left Handed,...,0.0,66.0,4.0,1/7 v DC,0.0,0.0,16.50,8.25,12.0,6.0

In [9]:
df.columns

Index(['Name', 'Team', 'Url', 'Type', 'ValueinCR', 'Full Name', 'Born', 'Age',
       'National Side', 'Batting Style', 'Bowling', 'Sport', 'MatchPlayed',
       'InningsBatted', 'NotOuts', 'RunsScored', 'HighestInnScore', '100s',
       '50s', '4s', '6s', 'BattingAVG', 'BattingS/R', 'CatchesTaken',
       'StumpingsMade', 'Ducks', 'R/O', 'InningsBowled', 'Overs', 'Maidens',
       'RunsConceded', 'Wickets', 'Best', '3s', '5s', 'BowlingAVG',
       'EconomyRate', 'S/R', 'Mtc'],
      dtype='object')

In [11]:
df['Sport']

0      NaN
1      IPL
2      IPL
3      NaN
4      IPL
      ...
232    IPL
233    NaN
234    NaN
235    NaN
236    IPL
Name: Sport, Length: 237, dtype: object